import type { Metadata } from "next";

import "./globals.css";
import { Jost } from "next/font/google";

const JostFont = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Designo Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${JostFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
